#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

~/Documents/Projects/theming/theme_changer

compton -f &
~/.config/polybar/launch.sh
