game:
  arch: win32
  exe: drive_c/Program Files/Wizards of the Coast/MTGA/MtgaLauncher.exe
  prefix: /home/anon/Games/magic-the-gathering-arena
system:
  env:
    DXVK_HUD: '0'
wine:
  Desktop: true
  WineDesktop: 1920x1080
  dxvk: false
  dxvk_version: '0.93'
  esync: true
  overrides:
    nvapi,nvapi64: disabled
  version: tkg-mtga-3.21-x86_64
